In [39]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics


In [40]:
## dataset:https://www.kaggle.com/farhanmd29/position-salaries

In [41]:
dataset='Position_Salaries.csv'
df=pd.read_csv(dataset)

In [42]:
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [43]:
df.isnull().sum()

Position    0
Level       0
Salary      0
dtype: int64

In [44]:
X=df.iloc[:,1:-1]
Y=df.iloc[:,-1]
X=np.array(X)
Y=np.array(Y)

In [45]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [46]:
Y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [47]:
tree=DecisionTreeClassifier(criterion="entropy")
tree.fit(X,Y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [48]:
treeprediction=tree.predict(X)
treeprediction

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [49]:
print("Accuracy:",metrics.accuracy_score(Y,treeprediction))

Accuracy: 1.0
