In [1]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm
from sklearn import preprocessing

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [3]:
train_data=pd.read_csv("train.csv") 
test_data=pd.read_csv("test.csv") 

In [5]:
df_train_predictors=pd.DataFrame({"bedrooms": train_data.bedrooms,
                                   "bathrooms": train_data.bathrooms,
                                   "sqft_living": train_data.sqft_living,
                                    "sqft_lot": train_data.sqft_lot,
                                   "floors": train_data.floors,
                                   "waterfront": train_data.waterfront,
                                   "view": train_data.view, 
                                   "condition": train_data.condition, 
                                   "grade": train_data.grade, 
                                   "sqft_above": train_data.sqft_above,
                                   "sqft_basement": train_data.sqft_basement, 
                                   "yr_built": train_data.yr_built, 
                                   "yr_renovated": train_data.yr_renovated,
                                   "lat": train_data.lat, 
                                   "long": train_data.long, 
                                   "sqft_living15": train_data.sqft_living15,
                                   "sqft_lot15": train_data.sqft_lot15})
df_train_response=pd.DataFrame({"price": train_data.price})

In [6]:
df_test_predictors=pd.DataFrame({"bedrooms": test_data.bedrooms,
                                   "bathrooms": test_data.bathrooms,
                                   "sqft_living": test_data.sqft_living,
                                    "sqft_lot": test_data.sqft_lot,
                                   "floors": test_data.floors,
                                   "waterfront": test_data.waterfront,
                                   "view": test_data.view, 
                                   "condition": test_data.condition, 
                                   "grade": test_data.grade, 
                                   "sqft_above": test_data.sqft_above,
                                   "sqft_basement": test_data.sqft_basement, 
                                   "yr_built": test_data.yr_built, 
                                   "yr_renovated": test_data.yr_renovated,
                                   "lat": test_data.lat, 
                                   "long": test_data.long, 
                                   "sqft_living15": test_data.sqft_living15,
                                   "sqft_lot15": test_data.sqft_lot15})

df_test_response=pd.DataFrame({"price": test_data.price})

In [7]:
X=df_train_predictors 
y=df_train_response 

In [8]:
std_scaleX = preprocessing.StandardScaler().fit(X) 
std_scaley = preprocessing.StandardScaler().fit(y)
X_train_scaled = std_scaleX.transform(X)
y_train_scaled = std_scaley.transform(y)

In [9]:
class linear_regression:
    def __init__(self,X,y,learning_rate,max_iter,training_set):
        self.X = X 
        self.y = y 
        self.learning_rate = learning_rate
        self.max_iter = max_iter 
        self.training_set = training_set
    
    def loss_function(self,X,y,theta):  
        N = len(y)
        MSE = (1/N) * np.sum(np.square(np.matmul(X, theta) - y))
        return(MSE)
        
    def gradient_descent(self):
        X1 = np.matrix(sm.add_constant(self.X))
        m,n = np.shape(X1)
        N = len(self.y)
        theta = np.ones(n)
        theta = np.reshape(theta, (n,1))
        for i in range(0, self.max_iter):
            loss = self.loss_function(X1,self.y,theta)
            predictions = np.matmul(X1,theta)
            step=((self.learning_rate*2)/N)*(X1.transpose().dot(predictions-self.y))
            theta=theta-step
        if self.training_set == True: 
            print("\nTraining Set: True")
        else: 
            print("\nTraining Set: False")
        print("Theta: \n", theta, " \nMSE: %f" % (loss), 
              "\nAlpha = %s" % self.learning_rate, "\nIterations: %s" % self.max_iter)
        return(theta)
    
    def predictor(self):
        X1 = np.matrix(sm.add_constant(self.X)) 
        theta = self.gradient_descent()
        predictions = np.matmul(X1,theta)
        return(predictions)

In [10]:
linreg = linear_regression(X_train_scaled,y_train_scaled,0.01,1000,training_set=True)    
predictions = linreg.predictor()


Training Set: True
Theta: 
 [[ 1.68297044e-09]
 [-3.62928083e-02]
 [ 4.96712979e-02]
 [-2.55880928e-02]
 [ 3.30943265e-02]
 [ 2.50621592e-02]
 [ 1.88087846e-01]
 [ 1.41482682e-01]
 [ 3.94761845e-02]
 [ 2.68512442e-01]
 [ 3.15477448e-01]
 [ 1.79806461e-01]
 [-1.94939678e-01]
 [ 5.23282008e-02]
 [ 2.31530769e-01]
 [-4.47110618e-03]
 [ 1.37239717e-01]
 [-3.92403753e-02]]  
MSE: 0.273483 
Alpha = 0.01 
Iterations: 1000


In [11]:
print(predictions)

[[-7.34434396e-01]
 [ 6.21739275e-01]
 [-2.69392273e-01]
 [-2.80840899e-01]
 [-2.10116693e-01]
 [ 2.53147025e+00]
 [-8.22124695e-01]
 [-9.02481579e-01]
 [-4.54305428e-01]
 [-6.79239582e-01]
 [ 7.33070949e-01]
 [-2.60866144e-01]
 [ 1.27911575e-01]
 [-5.44480307e-01]
 [ 1.55948123e-01]
 [ 1.18469325e+00]
 [-1.70060335e-01]
 [ 3.97541176e-02]
 [-7.75845794e-01]
 [-1.04831079e+00]
 [-1.22002746e-01]
 [ 1.81378894e+00]
 [-4.30782838e-01]
 [-1.19110446e+00]
 [-9.98705806e-02]
 [-8.66816830e-01]
 [ 6.41849150e-01]
 [ 3.23541649e-01]
 [-1.69886379e-01]
 [ 3.56850763e-01]
 [ 3.36399613e-02]
 [-5.34626777e-01]
 [ 2.70021244e-01]
 [ 6.44737394e-02]
 [-5.14922833e-01]
 [ 8.11398560e-01]
 [-5.90047267e-01]
 [ 7.64464518e-01]
 [-1.21616226e+00]
 [ 1.39373525e-01]
 [ 4.34491137e-01]
 [ 5.61832379e-01]
 [ 1.04349252e+00]
 [-4.69293617e-02]
 [-1.00499487e+00]
 [ 7.76586791e-01]
 [-1.46804016e+00]
 [ 5.70933918e-01]
 [-3.83499049e-01]
 [ 3.09329138e+00]
 [-9.00756102e-01]
 [ 3.26162826e-01]
 [-2.0947238

In [12]:
print(y_train_scaled)

[[-8.79747689e-01]
 [ 5.18249259e-02]
 [-1.00323042e+00]
 [ 2.46332337e-01]
 [-3.06933697e-02]
 [ 2.07647025e+00]
 [-7.74831571e-01]
 [-6.73599305e-01]
 [-8.57349866e-01]
 [-5.81797701e-01]
 [ 4.18736633e-01]
 [-1.54470813e-01]
 [-6.20109767e-01]
 [-3.54872388e-01]
 [ 2.82482700e-02]
 [ 3.81898108e-01]
 [-3.69607798e-01]
 [-1.04370419e-01]
 [-9.76706687e-01]
 [-8.55876325e-01]
 [-3.99078618e-01]
 [ 4.36045879e+00]
 [-6.93786816e-01]
 [-7.88977564e-01]
 [-5.64115209e-01]
 [-8.47035079e-01]
 [ 1.22771064e+00]
 [ 4.31998502e-01]
 [-2.42883273e-01]
 [ 5.85246765e-01]
 [ 1.77075910e-01]
 [-7.08522226e-01]
 [ 4.92413683e-01]
 [ 4.29836800e-02]
 [-5.83271242e-01]
 [ 5.17463879e-01]
 [ 8.71899097e-02]
 [ 3.52427288e-01]
 [-8.26405505e-01]
 [ 2.49279419e-01]
 [ 3.08221059e-01]
 [ 7.50283356e-01]
 [ 1.00665002e+00]
 [ 4.85045978e-01]
 [-6.23056849e-01]
 [-9.55291733e-02]
 [-9.13373895e-01]
 [ 7.79754176e-01]
 [-2.07518289e-01]
 [ 2.44485550e+00]
 [-8.61770489e-01]
 [-5.16961897e-01]
 [ 2.3454400